---
title: "2018 prediction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
setwd("~/Uni/3rd Year/Data Analysis and Modelling/Project 3/tennis")
library(readxl)
library(EloRating)
data18 <- read_excel("18.xlsx")
```

ids from 2018:
```{r}
r18 <- elo.seq(data18$Winner, data18$Loser, data18$Date, runcheck=FALSE)
```
now for elo ratings right before hand
```{r}
j<-(extract_elo(res00, "2017-12-30", IDs = r18$allids))
j <- j[sort(names(j))]
j
```

now to model the year and predict
```{r}
svalues18 <- c(1450,
1460,
1650,
1807,
1484,
1833,
1500,
1412,
1527,
1498,
1500,
1393,
1500,
1581,
1908,
1547,
1419,
1500,
1454,
1387,
1739,
1956,
1772,
1648, 
1783,
1500,
1980,
1756,
1907,
1585, 
1487,
1388,
1630, 
1389,
1490,
1540,
1406,
1500,                 
1643,
1415,
1469, 
1659,
1701, 
1500,
1485, 
1500,
1212,
1650,
1914,
1986,
1500,
1224,
1596,                
1500,
1808,
1778,                 
1507,
1537,
1467,
1441,
1637,                 
2235,                  
1883,
2312,
1390,                  
2296,
1837,
1487,                  
1787,
1500,                  
1456,                  
1552,
1663,                  
2003,                  
1699,
1876,
1653,
1580,
1550,
1431,                  
1668,
1222,
2447,                  
1885,
1974,                  
1705,
1837,
1318,
1430,
1495,
1474,
1500,
1620,
1407,                 
1983,                
1500,
1447,            
1231,            
1558,
1509,                  
1492,                  
2192,
1500,
1800,    
1342,
        
                 1436,                 1480,              1475,
       1706,                  1500,                  1843, 
      
                 1625,                 1374,                 1474,
     
                 1462,                 1409,                 1772,
      
                 1427,                 1576,                 1500,
     
                 1500,                 1500,                 1500,
     1500,                  1398,                  1406,
          
                 2036,                 1849,                 1555,
          
                 1497,                 1500,                 1394,
         
         1539,                1745,                1456, 
          
                 1500,                  1749,                  1500, 
          
                 1436,                 1500,                1670,
         1595,                  1442,                  1491,
          
                 1446,                 1273,                 1752,
         
                 1482,                 2048,                 1718,
         
                 1500,                 1500,                 1308,
         
                 1302,                 1847,                 1344,
        
                 1441,                  1473,                  1476, 
         1672,                 1450,                 1470,
          
                 1500,                 2082,                1694,
         
                 1668,                 1630,                 1442,
          
                 1442,                 1418,                 1872,
          
                 1610,                 1471,                 1691,
         
                 2006,                 1335,                 1701,
         
                 1500,                 1444,                 1824,
         
                 1957,                 1402,                 1837,
         
                 1689,                 1721,                 1298,
        
                 1471,                 1783,                 1228,
         
                 1400,                 1495,                 1956,
        1563,
        1500,
        1841,
         
                 1426,                 2034,                 2357,
         
                 1500,                 2003,                 1894,
         
                 1470,                 1384,                 1469,
         
                 1500,                 1637,                 1329,
        
                 1500,                 1398,                 1793,
              
                 1342,                 1389,                 1787,
             
                 1500,                 1230,                 1500,
          
                 1554,                 2024,                 1500,
          
                 1814,                 1500,                 1388,
     
                 1747,                 1987,                 1500,
     
                 1453,                 1670,                 1500,
     
                 1500,                 1601,                 1357,
     
                 1805,                 1383,                 1499,
     
                 1413,                 1497,                 1500,
     
                 1384,                 1465,                 1974,
     
                 1846,                 1748,                 1454,
     
                 1500,                 1354,                 1466,
     
                 1702,                 1289,                 1186,
     
                 1502,                 2131,                 1486,
     
                 1713,                 1366,                 1694,
     
                 1660,                 1784,                 1809,
     
                 1500,                 1866,                 1753,
                 1253,                  1635,                  1409, 

                 1795,                 1350,                1500,
 
                 1411,                 2030,                 1280,
 
                 1500,                 1370,                 1920,
 
                 1671,                 1320,                 1500,
 
                 1500,                 2057,                 1326,

                 1429,                 1225,                 1363,
 
                 1661,                 1507,                 1500,
 
                 1696,                 1383,                 1193, 
2035,                  1823) ; names(svalues18) <- c(r18$allids)
```

```{r}
r18test <- elo.seq(data18$Winner, data18$Loser, data18$Date, startvalue = svalues18, runcheck=FALSE)
correctly_predicted(r18test)
```

seperate syrfaces

```{r}
hard0 <- filter(data18, Surface == "Hard")
grass0 <- filter(data18, Surface == "Grass")
clay0 <-filter(data18, Surface == "Clay")
```



```{r}
table(data17$Series)
myk1 <- list( "ATP250" = 12.5 , "ATP500" = 25, "Grand Slam" = 100, "International" = 5, "International Gold" = 5, "Masters"= 75, "Masters 1000" = 50, "Masters Cup" = 50)
res17k <- elo.seq(data17$Winner, data17$Loser, data17$Date, k = 37.13131, intensity = data17$Series ,runcheck = FALSE)
summary(res17k)
```
```{r}
ek17<- extract_elo(res17k)
ek17<- ek17[1:24]
ek17
```

data17 <- read_excel("17.xlsx")
r17 <- elo.seq(data17$Winner, data17$Loser, data17$Date, startvalue=1500, k =  runcheck=FALSE)
```

```{r}
e17<- extract_elo(r17)
t <- e17[1:24]
t
```
