---
title: "TennisProject"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(BradleyTerry2)
library(dplyr)
library(tidyverse)
X2001 <- read_excel("2001.xls")
X2002 <- read_excel("2002.xls")
X2003 <- read_excel("2003.xls")
X2004 <- read_excel("2004.xls")
X2005 <- read_excel("2005.xls")
X2006 <- read_excel("2006.xls")
X2007 <- read_excel("2007.xls")
X2008 <- read_excel("2008.xls")
X2009 <- read_excel("2009.xls")
X2010 <- read_excel("2010.xls")
X2011 <- read_excel("2011.xls")
X2012 <- read_excel("2012.xls")
X2013 <- read_excel("2013.xlsx")
X2014 <- read_excel("2014.xlsx")
X2015 <- read_excel("2015.xlsx")
X2016 <- read_excel("2016.xlsx")
X2017 <- read_excel("2017.xlsx")
X2018 <- read_excel("2018.xlsx")
X2019 <- read_excel("2019.xlsx")
X2020 <- read_excel("2020.xlsx")


```

```{r}
Y2000<-read_excel("2001.xls")
```


## Bradley Terry Modelling



```{r pressure, echo=FALSE}
data <- X2017
data <- data %>%
dplyr::mutate(
    player1 = factor(Winner, levels = unique(c(Winner, Loser))),
    
    player2 = factor(Loser, levels = levels(player1)),
    
    
    
  )

fit<- BTm(1,player1,player2,data = data)


##plot

abilities <- BTabilities(fit)

abilities <- data.frame(
  Name = rownames(abilities),
  Ability = abilities[,1],
  SE = abilities[,2]
)

#order
abilities$Name <- factor(abilities$Name, levels = abilities$Name[order(abilities$Ability)])
df<-abilities[order(-abilities$Ability),]
Rank = 1:307
df$new_col <- Rank
#top 20
top20 <-subset(df,Rank<21)
pr<-ggplot(top20,aes(Name,Ability,ymin=Ability-SE,ymax=Ability+SE))+geom_pointrange()
a<- (pr + coord_flip())

#Players with enough data
GoodData <- subset(df,SE<2)
p<-ggplot(GoodData,aes(Name,Ability))+geom_point()
p+ coord_flip()
  #error plot
pr<-ggplot(GoodData,aes(Name,Ability,ymin=Ability-SE,ymax=Ability+SE))+geom_pointrange()
b<-(pr + coord_flip())


#all data
  #point plot
bp<-ggplot(abilities,aes(Name,Ability))+geom_point()
c<-(bp+ coord_flip())
  #error plot
pr<-ggplot(abilities,aes(Name,Ability,ymin=Ability-SE,ymax=Ability+SE))+geom_pointrange()
d<-(pr + coord_flip())
```

Introduce court surface co-variate

```{r}
data2 <- X2017
data2 <- data2 %>%
dplyr::mutate(
    player1 = factor(Winner, levels = unique(c(Winner, Loser))),
    
    player2 = factor(Loser, levels = levels(player1)),
    
  )
dataHard<-subset(data2,Surface=="Hard")
dataClay<-subset(data2,Surface=="Clay")
dataGrass<-subset(data2,Surface=="Grass")

fitH<- BTm(1,player1,player2,data = dataHard)
fitC<- BTm(1,player1,player2,data = dataClay)
fitG<- BTm(1,player1,player2,data = dataGrass)

##plot

abilitiesH <- BTabilities(fitH)
abilitiesC <- BTabilities(fitC)
abilitiesG <- BTabilities(fitG)

abilitiesH <- data.frame(
  Name = rownames(abilitiesH),
  Ability = abilitiesH[,1],
  SE = abilitiesH[,2]
)
abilitiesC <- data.frame(
  Name = rownames(abilitiesC),
  Ability = abilitiesC[,1],
  SE = abilitiesC[,2]
)
abilitiesG <- data.frame(
  Name = rownames(abilitiesG),
  Ability = abilitiesG[,1],
  SE = abilitiesG[,2]
)

#order
abilitiesH$Name <- factor(abilitiesH$Name, levels = abilitiesH$Name[order(abilitiesH$Ability)])

abilitiesC$Name <- factor(abilitiesC$Name, levels = abilitiesC$Name[order(abilitiesC$Ability)])

abilitiesG$Name <- factor(abilitiesG$Name, levels = abilitiesG$Name[order(abilitiesG$Ability)])

dfH<-abilitiesH[order(-abilitiesH$Ability),]
dfC<-abilitiesC[order(-abilitiesC$Ability),]
dfG<-abilitiesG[order(-abilitiesG$Ability),]


Rank = 1:307
dfH$new_col <- Rank
dfC$new_col <- Rank
dfG$new_col <- Rank

#top 10
top10H <-subset(dfH,Rank<11)
prH<-ggplot(top10H,aes(Name,Ability,ymin=Ability-SE,ymax=Ability+SE))+geom_pointrange()
aH<- (prH + coord_flip()+ ggtitle("Hard Surface"))

top10C <-subset(dfC,Rank<11)
prC<-ggplot(top10C,aes(Name,Ability,ymin=Ability-SE,ymax=Ability+SE))+geom_pointrange()
aC<- (prC + coord_flip()+ ggtitle("Clay Surface"))

top10G <-subset(dfG,Rank<11)
prG<-ggplot(top10G,aes(Name,Ability,ymin=Ability-SE,ymax=Ability+SE))+geom_pointrange()
aG<- (prG + coord_flip()+ ggtitle("Grass Surface"))

#Players with enough data
GoodData <- subset(df,SE<2)
p<-ggplot(GoodData,aes(Name,Ability))+geom_point()
p+ coord_flip()
  #error plot
pr<-ggplot(GoodData,aes(Name,Ability,ymin=Ability-SE,ymax=Ability+SE))+geom_pointrange()
b<-(pr + coord_flip())


#all data
  #point plot
bp<-ggplot(abilities,aes(Name,Ability))+geom_point()
c<-(bp+ coord_flip())
  #error plot
pr<-ggplot(abilities,aes(Name,Ability,ymin=Ability-SE,ymax=Ability+SE))+geom_pointrange()
d<-(pr + coord_flip())



```



